// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class Settings
{
	private final IMendixObject settingsMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.Settings";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ShowAdditionalData("ShowAdditionalData");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public Settings(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.Settings"));
	}

	protected Settings(IContext context, IMendixObject settingsMendixObject)
	{
		if (settingsMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.Settings", settingsMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.Settings");

		this.settingsMendixObject = settingsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'new Settings(Context)' instead. Note that the constructor will not insert the new object in the database.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Settings create(IContext context) throws CoreException
	{
		IMendixObject mendixObject = Core.create(context, "MyFirstModule.Settings");
		return new myfirstmodule.proxies.Settings(context, mendixObject);
	}

	/**
	 * @deprecated Use 'Settings.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.Settings initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.Settings.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.Settings initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Settings(context, mendixObject);
	}

	public static myfirstmodule.proxies.Settings load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Settings.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Settings> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<myfirstmodule.proxies.Settings> result = new java.util.ArrayList<myfirstmodule.proxies.Settings>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MyFirstModule.Settings" + xpathConstraint))
			result.add(myfirstmodule.proxies.Settings.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of ShowAdditionalData
	 */
	public final Boolean getShowAdditionalData()
	{
		return getShowAdditionalData(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowAdditionalData
	 */
	public final Boolean getShowAdditionalData(IContext context)
	{
		return (Boolean) getMendixObject().getValue(context, MemberNames.ShowAdditionalData.toString());
	}

	/**
	 * Set value of ShowAdditionalData
	 * @param showadditionaldata
	 */
	public final void setShowAdditionalData(Boolean showadditionaldata)
	{
		setShowAdditionalData(getContext(), showadditionaldata);
	}

	/**
	 * Set value of ShowAdditionalData
	 * @param context
	 * @param showadditionaldata
	 */
	public final void setShowAdditionalData(IContext context, Boolean showadditionaldata)
	{
		getMendixObject().setValue(context, MemberNames.ShowAdditionalData.toString(), showadditionaldata);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return settingsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Settings that = (myfirstmodule.proxies.Settings) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.Settings";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
