// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class TimerItems
{
	private final IMendixObject timerItemsMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "MyFirstModule.TimerItems";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CurrentTimeString("CurrentTimeString"),
		TimerObjects_Camera("MyFirstModule.TimerObjects_Camera");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public TimerItems(IContext context)
	{
		this(context, Core.instantiate(context, "MyFirstModule.TimerItems"));
	}

	protected TimerItems(IContext context, IMendixObject timerItemsMendixObject)
	{
		if (timerItemsMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("MyFirstModule.TimerItems", timerItemsMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a MyFirstModule.TimerItems");

		this.timerItemsMendixObject = timerItemsMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TimerItems.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static myfirstmodule.proxies.TimerItems initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return myfirstmodule.proxies.TimerItems.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.TimerItems initialize(IContext context, IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.TimerItems(context, mendixObject);
	}

	public static myfirstmodule.proxies.TimerItems load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.TimerItems.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.TimerItems> load(IContext context, String xpathConstraint) throws CoreException
	{
		java.util.List<myfirstmodule.proxies.TimerItems> result = new java.util.ArrayList<myfirstmodule.proxies.TimerItems>();
		for (IMendixObject obj : Core.retrieveXPathQuery(context, "//MyFirstModule.TimerItems" + xpathConstraint))
			result.add(myfirstmodule.proxies.TimerItems.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of CurrentTimeString
	 */
	public final String getCurrentTimeString()
	{
		return getCurrentTimeString(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentTimeString
	 */
	public final String getCurrentTimeString(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.CurrentTimeString.toString());
	}

	/**
	 * Set value of CurrentTimeString
	 * @param currenttimestring
	 */
	public final void setCurrentTimeString(String currenttimestring)
	{
		setCurrentTimeString(getContext(), currenttimestring);
	}

	/**
	 * Set value of CurrentTimeString
	 * @param context
	 * @param currenttimestring
	 */
	public final void setCurrentTimeString(IContext context, String currenttimestring)
	{
		getMendixObject().setValue(context, MemberNames.CurrentTimeString.toString(), currenttimestring);
	}

	/**
	 * @return value of TimerObjects_Camera
	 */
	public final myfirstmodule.proxies.Camera getTimerObjects_Camera() throws CoreException
	{
		return getTimerObjects_Camera(getContext());
	}

	/**
	 * @param context
	 * @return value of TimerObjects_Camera
	 */
	public final myfirstmodule.proxies.Camera getTimerObjects_Camera(IContext context) throws CoreException
	{
		myfirstmodule.proxies.Camera result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TimerObjects_Camera.toString());
		if (identifier != null)
			result = myfirstmodule.proxies.Camera.load(context, identifier);
		return result;
	}

	/**
	 * Set value of TimerObjects_Camera
	 * @param timerobjects_camera
	 */
	public final void setTimerObjects_Camera(myfirstmodule.proxies.Camera timerobjects_camera)
	{
		setTimerObjects_Camera(getContext(), timerobjects_camera);
	}

	/**
	 * Set value of TimerObjects_Camera
	 * @param context
	 * @param timerobjects_camera
	 */
	public final void setTimerObjects_Camera(IContext context, myfirstmodule.proxies.Camera timerobjects_camera)
	{
		if (timerobjects_camera == null)
			getMendixObject().setValue(context, MemberNames.TimerObjects_Camera.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.TimerObjects_Camera.toString(), timerobjects_camera.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return timerItemsMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.TimerItems that = (myfirstmodule.proxies.TimerItems) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "MyFirstModule.TimerItems";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
